apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-eta-deploy
  labels:
    app: medicure-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-eta-app
  template:
    metadata:
      labels:
        app:medicure-eta-app
    spec:
      containers:
      - name: medicure-eta-container
        image: vijethaa/medicure-eta-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name:medicure-eta-np-service
  labels:
    app: medicure-eta-app
spec:
  selector:
    app: healthcare-eta-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
